#  (C) Copyright
#  Sony Computer Entertainment, Inc.,
#  Toshiba Corporation,
#  International Business Machines Corporation,
#  2005.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. 

#
# This file is based on execute.exp in c-torture.
#

# Exit immediately if this isn't an SPU target.
if ![istarget spu-*-*] then {
  return
}

if $tracelevel then {
    strace $tracelevel
}

# load support procs
load_lib c-torture.exp

#
# main test loop
#

foreach src [lsort [glob -nocomplain $srcdir/$subdir/*.c]] {
    # If we're only testing specific files and this isn't one of them, skip it.
    if ![runtest_file_p $runtests $src] then {
	continue
    }

    c-torture-execute $src
}
